<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Document</title>
</head>
<body>
  <script>
    // function fun1()
    // {
    //   return new Promise(function(resolved)
    // {
    //   setTimeout(function()
    //   {
    //     resolved();
    //   },1000)
    // })
    // }
    // function fun2()
    // {
    //   return new Promise(function(resolved)
    // {
    //   setTimeout(function()
    //   {
    //     resolved();
    //   },1000)
    // })
    // }
    // function fun3()
    // {
    //   return new Promise(function(resolved)
    // {
    //   setTimeout(function()
    //   {
    //     resolved();
    //   },1000)
    // })
    // }

    // old then and catch method this will be difficult when we write so many functions, it is difficult to find where the error occurs
//     fun1().then(function()
//     {
//   console.log("Fun-1 Completed")
//   fun2().then(function()
//   {
//     console.log("Fun-2 Completed")
//     fun3().then(function()
//     {
//       console.log("Fun-3 Completed")
//     })
//   })
// })

function fun1()
    {
      return new Promise(function(resolved)
    {
      setTimeout(function()
      {
        resolved(1);
      },1000)
    })
    }
    function fun2(value)
    {
      return new Promise(function(resolved)
    {
      setTimeout(function()
      {
        resolved(value+1);
      },1000)
    })
    }
    function fun3(value)
    {
      return new Promise(function(resolved)
    {
      setTimeout(function()
      {
        resolved(value+1);
      },1000)
    })
    }

async function Execute()
{
  try{
    const result1 = await  fun1();
    const result2 = await fun2(result1);
    const result3 = await fun3(result2);
    console.log(result3);
  }
  
  catch(err)
  {
    console.log(err);
  }
}
Execute();
  </script>

  <!-- example-1 -->
   <script>
    const result = new Promise(function(resolve,rejected)
    {
       var x = 10;
       if(x==10)
       {
        resolve();
       }
       else{
        rejected();
       }
    })
    result.catch(function()
  {
    console.log("Not Eligible");
  })
    result.then(function()
  {
    console.log("Eligible")
  })
   </script>
   <script>
    const result1 = new Promise(function(resolve,rejected)
    {
       var f = 10;
    })
    console.log(result1);
   </script>
</body>
</html>